### ISSUE TITLE
time crate dependency

### ISSUE THREAD

**Issue by lnicola** [alexcrichton/cookie-rs#109]
This might be a stupid question, but does the `time` crate offer anything in addition to `std::time`? Replacing it would be a breaking change, but is there more to it?

**Comment by SergioBenitez** [comment]
In general, `time` on crates is a maintained/expanded version of `std::time`. It's got a bunch of helpful functions and methods that `std::time` doesn't, and it's generally agreed that one should use `time` over `std::time`.

**Comment by lnicola** [comment]
> In general, time on crates is a maintained/expanded version of std::time.

That's not how I see it; the repository is at `rust-lang-deprecated/time` and the README says:

> This library is no longer actively maintained, but bugfixes will be added (details).

> it's generally agreed that one should use time over std::time.

Maybe, but I've never seen that advice.

> It's got a bunch of helpful functions

Got it, `strptime` and `strftime`. There's no equivalent functionality in `std::time`.

**Comment by jhpratt** [comment]
@SergioBenitez `time`'s repository mentions that `chrono` should be used instead, as `time` is no longer maintained.

**Comment by SergioBenitez** [comment]
@jhpratt Certainly, but `chrono` is a much bigger, much more opinionated crate than we need. That being said, I have no strong opinions on the matter. As long as it is user-friendly, I'm open to migration PRs.

**Comment by jhpratt** [comment]
@onx2 I actually wound up taking over the time crate shortly after my previous comment. It's now a rough equal to chrono, so no reason to avoid one or the other.

**Comment by onx2** [comment]
It seems like all the other packages I'm using prefer chrono or at least provide a feature for it. Would it be possible to add the option for chrono to this package? Or if that's something you don't want to do, would you suggest using both `time` and `chrono`?

**Comment by jhpratt** [comment]
I'm not a maintainer, but I'm pretty sure that's something that wouldn't even be feasible. sqlx and async-graphql use the feature flags to enable third-party implementations whereas cookie relies on it in the API itself — basically you _couldn't_ have both enabled at the same time, and the features wouldn't be additive as required by cargo.

There's nothing wrong with using both crates, though I can imagine it may get a little confusing at times.

**Comment by onx2** [comment]
Got it, thanks for the clarification! I'll use `time` for this crate and `chrono` for the others 😄

**Comment by TheCGDF** [comment]
> @jhpratt Certainly, but `chrono` is a much bigger, much more opinionated crate than we need. That being said, I have no strong opinions on the matter. As long as it is user-friendly, I'm open to migration PRs.

Using different packages makes others write more codes to cast types.

Your `cookie-rs` keeps small and others' codes got bigger.

I still think excessive pursuit of lightweight is toxic.

**Comment by jplatte** [comment]
Coming back to this, how about continuing to use `time` internally for ergonomics, but removing it from the public API? I don't see how time's `Duration` that allows negative values is useful for setting `max-age`. Mabye there's other uses of `time` types in public API?
