### ISSUE TITLE
Don't specify explicit versions for oft-fixed dependencies like rustc-serialize

### ISSUE THREAD

**Issue by reem** [alexcrichton/cookie-rs#22]
Or update them super frequently, which is probably a huge pain. 

Right now the explicit dependency on an old version is causing build failures of this package and subsequently hyper.

**Comment by alexcrichton** [comment]
Depending on `*` is generally an antipattern as it's far too permissive and it's not actually what one means. This crate used to depend on the `0.1` *channel* of rustc-serialize, not any particular version. All minor updates to the crate that were not API-breaking changes, and they were all automatically picked up.

Once a breaking change was made to rustc-serialize, this crate needs to manually opt-in to 0.2 as it's not sure that it's compatible or not. In this case it was as the breakage was minor. Right now this is following the 0.2 channel of rustc-serialize, and I do not want to switch it to something more permissive than that.

**Comment by reem** [comment]
@alexcrichton That seems like a reasonable approach. I agree that `*` is an anti pattern and I anticipate that its use will drop dramatically after 1.0 and when projects start to hit 1.0 themselves.
