### ISSUE TITLE
Use an AEAD cipher instead of AES-CBC + HMAC-SHA1

### ISSUE THREAD

**Issue by DemiMarie** [alexcrichton/cookie-rs#50]
cookie-rs currently uses AES-256-CBC and then HMAC-SHA1 in encrypt-then-MAC.  This is secure, since AES-256-CBC and HMAC-SHA1 are both individually secure and because they are used in encrypt-then-MAC.

However, neither AES-256-CBC nor HMAC-SHA1 is fast, even when AES is hardware accelerated (due to the serial nature of CBC mode).  ChaCha20-Poly1305 is much faster.

Again, cookie-rs's current crypto is not _insecure_, just slow.

**Comment by alexcrichton** [comment]
Ideally this'd actually be configurable rather than only hardcoding one and calling it a day, but I'm somewhat hesitant to deviate away from the source of this, Rails, which is probably much more experienced than I :)

**Comment by frewsxcv** [comment]
Opened a PR: https://github.com/alexcrichton/cookie-rs/pull/68.

**Comment by briansmith** [comment]
There's another PR for this: #76.
