### ISSUE TITLE
Upgrade openssl dependency

### ISSUE THREAD

**Issue by zsck** [alexcrichton/cookie-rs#53]
Currently, cookie-rs's [Cargo.toml](https://github.com/alexcrichton/cookie-rs/blob/master/Cargo.toml) specifies using [Rust-OpenSSL](https://github.com/sfackler/rust-openssl) version `0.7.0`.  At the time of this writing, the [latest release](https://github.com/sfackler/rust-openssl/releases) is version `0.8.2`, which includes a number of bug fixes that, [in some applications](https://github.com/mattnenterprise/rust-ftp/pull/51) has resolved some functional failings.

I'd like to ask for cookie-rs to adopt these changes and upgrade to the latest version.

**Comment by alexcrichton** [comment]
Sure!
