### ISSUE TITLE
Implement Debug for CookieJar?

### ISSUE THREAD

**Issue by alexreg** [alexcrichton/cookie-rs#56]
Is there any good reason CookieJar doesn't derive/implement the Debug trait?

**Comment by alexcrichton** [comment]
Nah just hasn't been done yet! Want to send a PR?

**Comment by alexreg** [comment]
I could try! Never actually hacked on Rust before, just a couple of compiler plugins. Feel free to give me some pointers. :)

**Comment by alexcrichton** [comment]
Sure! You'd probably just want to add the impl to jar.rs and can probably just iterate over the root's map and then call `find` on each key to decode everything, printing out all the results.

**Comment by alexreg** [comment]
Thanks. Will give it a go on the weekend with any luck.

**Comment by alexreg** [comment]
Oh, I’m being silly. I thought I was replying to another issue! This is indeed simple. Thanks for the tip though.

**Comment by untitaker** [comment]
Can be closed.

**Comment by alexcrichton** [comment]
Indeed!
