### ISSUE TITLE
Please use rust-crypto to ease compiling on Windows

### ISSUE THREAD

**Issue by fatihpense** [alexcrichton/cookie-rs#59]
Thanks for the library! As the title mentions I am having problems compiling openssl with rust. rust-crypto crate has HMAC implementation so is this possible?

**Comment by fatihpense** [comment]
Documentation states that: "Rust-Crypto has not been thoroughly audited for correctness, so any use where security is important is not recommended at this time." So I think this issue can be closed with valid concerns. :)

**Comment by alexcrichton** [comment]
Thanks for the report! It is indeed a bummer how difficult it is to get OpenSSL working on Windows. I wonder if perhaps though we could move to the *ring* project? That I believe is more vetted in the sense that it's just BoringSSL's code?

**Comment by fatihpense** [comment]
By the way, I got it working. The solution, for now, is installing OpenSSL 1.0.* Because libraries look for libeay32.dll & libssl32.dll .

I don't have much experience regarding crypto. So I will listen where this conversation goes :)

**Comment by alexcrichton** [comment]
Ok! In that case I'm going to close this for now. Thanks for the report though!
