### ISSUE TITLE
Feature: Sign entire cookie, not just value

### ISSUE THREAD

**Issue by untitaker** [alexcrichton/cookie-rs#62]
I'd like signatures on cookies to include expiration date and path as well. The signature could still be inside the cookie value.

I would love to prepare a PR for this, but I'm unsure how to design this in a backwards compat way (or if that is even necessary).

**Comment by alexcrichton** [comment]
Sounds plausible to me! Could either make this a config option or do a major version bump as behavior changed, either way's fine by me

**Comment by untitaker** [comment]
PR: #63
