### ISSUE TITLE
Implement Send?

### ISSUE THREAD

**Issue by alexreg** [alexcrichton/cookie-rs#64]
Can/should the `CookieJar` type (unsafely) implement `Send`? Or perhaps one of its component types. It's rather prohibitive right now that it doesn't.

**Comment by alexcrichton** [comment]
A "root" jar which is sendable could be added perhaps? Or otherwise in general the "child" jars like signed and encrypted could become separate types to allow the root to get passed around.

**Comment by alexreg** [comment]
Indeed, I think that would be the way to do it. Maybe worth creating a newtype for a root jar, for this purpose?

**Comment by alexcrichton** [comment]
Yeah something like that, probably with `Deref` to ensure everything has the same API.

**Comment by alexreg** [comment]
Right. That sounds fair.

I would normally be glad to submit a PR, but I’m not so confident when it comes to making sure things are manually Send/Sync-safe. Mind if I leave this to you? I suspect you’ll be doing a 0.4 release soon anyway...

**Comment by alexcrichton** [comment]
Oh there's no unsafe code here so there's no need to worry about whether it's send/sync-safe, it'll all automatically fall out. The reason it's not `Send` today is because transitively it may contain `&'a RefCell<T>` which isn't safe to send across threads.

**Comment by alexreg** [comment]
Hmm. So the `RefCell` is just an internal implementation detail, and references to it can’t be leaked if you’re sending the root jar?

Well, I’ll probably let you make this change anyway if that’s alright. :-)

**Comment by alexcrichton** [comment]
Right yeah, only "child jars" have a reference to a `RefCell`. A root jar owns the `RefCell` itself and as a result is sendable.
