### ISSUE TITLE
Remove cookies are missing Path and Domain

### ISSUE THREAD

**Issue by kballard** [alexcrichton/cookie-rs#75]
When a cookie is removed from the Jar, it only records the cookie's name. So when the Set-Cookie header is generated to clear the cookie, the header does not have the Path or Domain parameters, even if the original cookie had them. This is a problem because the new Set-Cookie header only overwrites the previous cookie if the Path and Domain parameters match.

**Comment by kballard** [comment]
The solution here is to actually find the original cookie in the Jar and store that in the removed_cookies list instead of just storing the cookie name. This would have the side-effect of fixing what I consider to be another bug, which is that `empty_jar.remove("foo")` produces a Set-Cookie header even though there was no original cookie by that name.

**Comment by SergioBenitez** [comment]
The browser does not pass along any other information besides the name and value of the cookie. As a result, unless `cookie` is storing cookies, proper deletion is simply impossible with the current API. I believe that the `delete` method should instead take in a `Cookie` and specify that it should have all of the original fields set. We can then set the `max_age` and `expires` fields properly.

**Comment by kballard** [comment]
Oh crud, you're right. Or, if we're happy with the current behavior of Max-Age and Expires when removing, we could just have `remove()` take two more optional parameters for path and domain, e.g.

```rust
fn remove<N, P, D>(&self, cookie_name: N, path: Option<P>, domain: Option<D>)
    where N: Into<Cow<'static, str>>,
          P: Into<Cow<'static, str>>,
          D: Into<Cow<'static, str>>
```

**Comment by SergioBenitez** [comment]
Yeah, we could do that as well.

I'll be revamping `CookieJar` in the near future, and I'll make sure to fix this along the way.
