### ISSUE TITLE
Support for SameSite

### ISSUE THREAD

**Issue by bbigras** [alexcrichton/cookie-rs#80]
Like many I read the [Cross-Site Request Forgery is dead!](https://scotthelme.co.uk/csrf-is-dead/) blog post 2 days ago and I thought it would be nice to use. It's currently only supported by Chrome.

**Comment by SergioBenitez** [comment]
Agreed! The SameSite cookie field is still a draft, however, and its design may change before being finalized.

@alexcrichton I considered adding support for this field via a `draft` feature. What do you think?

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by SergioBenitez** [comment]
Hoping to get this in for 0.7.1.

**Comment by SergioBenitez** [comment]
Looks like @alexcrichton skipped 0.7.1. Hehe. Well, 0.7.3 it is.

**Comment by SergioBenitez** [comment]
This was released in 0.7.3.

**Comment by bbigras** [comment]
Awesome, thanks!!
