### ISSUE TITLE
Discussion: Could parsing and signing be split into two separate crates?

### ISSUE THREAD

**Issue by zofrex** [alexcrichton/cookie-rs#81]
Can I open a discussion on potentially splitting this into two separate crates, one for cookie jars + signing, and one for general purpose cookie parsing?

At it is right now this crate does two quite different things:

- Parse cookies from strings into useful structs and vice-versa - general utility useful to almost any web application
- Manage cryptographically signed cookies - much more specific and opinionated feature, not useful in all web applications

Even if un-used, the second feature existing comes with a price - Hyper no longer imports this crate due to the optional dependency on openssl. Upshot: it's now no longer possible to parse cookies out of the box in Iron.

If the features were split into two different crates then crates like Hyper (and anyone else only wanting to parse cookies, not sign them) could continue using the nice API here for that, and people who still want both would be unaffected (there's no reason the public API of _this_ crate would need to change at all).

**Comment by SergioBenitez** [comment]
In `0.7`, `cookie` will be using _ring_ for it's crypto (https://github.com/alexcrichton/cookie-rs/pull/68). Unlike `openssl`, `ring` has no `-sys` dependencies, making it a fairly light dependency. The only caveat is that it requires Visual Studio to be installed on Windows to build, but that itself is changing. In short, `ring` should be as easy to build as any other Rust library.

My impression from speaking with @seanmonstar is that this would resolve his qualms about including `cookie` as a dependency in `reqwest`. Removing the dependency from `hyper`, I believe, was for this reason _and_ others. I personally would not like to see `cookie` be a dependency of `hyper`.

`secure` is an _optional_ feature. If you don't want the signing/encryption features, then simply don't enable the feature. I don't see the difference between having `secure` be a feature and having it be a separate crate.

**Comment by alexcrichton** [comment]
Yeah the historical events here were unfortunate, but it should be getting much better soon! With *ring* coming soon as well as a default-off feature I think this'll effectively be solved, so I'm going to close this.
