### ISSUE TITLE
Rename jar to session or something else?

### ISSUE THREAD

**Issue by erickt** [alexcrichton/cookie-rs#94]
I was talking to @seanmonstar in #hyper earlier tonight, and he said that he wasn't sure if cookie::jar was named correctly:

> I think the jar in cookie is not what we typically think of for a jar usually a jar is what the user agent has, but the cookie crate's version is more like what many would think of as a session
...
> usually, a session is when a server receives a request, looks in its cookie headers for some state, and then the server possibly updates that session, which results in probably new Set-Cookie headers being sent
> its only for a single user, and their interaction with that specific server
> whereas a jar, in user agents, holds all the cookies the browser has seen for that user, for any website

If it's the case that "jar" is mainly used for user agents, but the current module is designed for servers, should we consider renaming this module to something else?

**Comment by SergioBenitez** [comment]
The `CookieJar` in this crate can be used for clients or servers, or at least that's the intention. I don't see why "jar" should connote being used one way or another; it's just a collection of cookies with a fun name. But, as "evidence", Rails calls their cookie collection a [`CookieJar`](http://www.rubydoc.info/docs/rails/ActionDispatch/Cookies/CookieJar) as well - I believe that's where this library got the name from.
