### ISSUE TITLE
Update Ring

### ISSUE THREAD

**Issue by lancecarlson** [alexcrichton/cookie-rs#97]
Please update ring to the latest.

https://github.com/alexcrichton/cookie-rs/pull/96

@SergioBenitez @alexcrichton

**Comment by lholden** [comment]
Yeah... this is a bit of an issue as ring ends up having native code linked. When this happens, the rust compiler bails if you have another dep on a different version.

**Comment by SergioBenitez** [comment]
Done.

**Comment by Libbum** [comment]
This needs to happen again. (See briansmith/ring/issues/598, briansmith/ring/issues/607)

**Comment by SergioBenitez** [comment]
I'm fully aware, but there's no new stable release of `ring`, only an `alpha`. Furthermore, once https://github.com/briansmith/ring/pull/619 lands, we can update `ring` without a new major release bump. I'll hold off until either one of these occurs.
